import Head from "next/head"
import { Header } from "../guitarla/Header"

export const LayoutsIndex = ({children, page, title='GuitarLA'}) => {
  return (
    <>
        <Head>
            <title>{title} - {page}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        {children}
    </>
  )
}
